"""
Django settings for json管理器 project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# 爬虫休息时间间隔
REST_TIME = 7200

# base_dir=webui
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 微博爬虫根目录
WEIBO_DIR = os.path.abspath(os.path.join(BASE_DIR,  "..", "weibo_new"))
# 新闻爬虫根目录
CRAWLER_DIR = os.path.abspath(os.path.join(BASE_DIR,  "..", 'news'))
# 存储爬虫配置的目录
JSON_DIR = os.path.join(CRAWLER_DIR, "universal", "configs")
# 存储备份爬虫配置的目录
BAK_JSON_DIR = os.path.join(CRAWLER_DIR, "universal", "bakconfigs")
HOME = os.path.abspath(os.path.join(os.path.expanduser("~"), "json_manager"))
LOG_PATH = os.path.join(HOME, "logs")
EXCEPTION_PATH = os.path.join(HOME, "exception")
# 如果文件夹不存在，需要新建文件夹
for i in (HOME, LOG_PATH, EXCEPTION_PATH, BAK_JSON_DIR):
    if not os.path.exists(i):
        os.mkdir(i)

# JSONSchema文件所在位置
SCHEMA_JSON = os.path.join(BASE_DIR, "main", "static", "crawler-schema.json")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u^!$=8uue7ic=j1ng9nn32^ulfl5nl1$%e7c!q&0u%=cnw1_03'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'json_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'json_manager.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'standard': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'filters': {
    },
    'handlers': {
        'mail_admins': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            'filename': os.path.join(LOG_PATH, 'request.log'),
            'encoding': 'utf8',
            'backupCount': 14
        },
        'user_op': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_PATH, 'user_op.log'),
            'formatter': 'standard',
            'encoding': 'utf8',
            'backupCount': 14
        },
    },
    'loggers': {
        'django': {
            'handlers': ['mail_admins'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'user_op': {
            'handlers': ['user_op'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
# 时区及编码配置
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
# 静态文件
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
